google-summer-of-code-2018/index.md

updated hrefs to markdown for GSoC 2017 index.md

updated hrefs to markdown for GSoC 2017 index.md

---

google-summer-of-code-2017/index.md

changed href to markdown for GSoC 2017 index.md

changed href to markdown for GSoC 2018 index.md

---

fenics18/index.md

Changed herf to markdown syntax for all links in fenics18 index.md

Changed herf to markdown syntax for all links in fenics18 index.md

---

fenics18/index.md

markdownify links

---

.github/workflows/run-tests.yml
_test/test_links.py
_test/test_version_numbers.py
book/index.md
community/index.md
documentation/index.md
fenics-2021/index.md
fenics17/index.md
index.md
tutorial/index.md

Add test that links within the website point to pages that exist

---

assets/css/customsty.css

Make mathjax scroll when its too wide

---

_includes/_developer.html
_test/test_governance.py
assets/css/customsty.css
governance/advisory-board.md
governance/steering-council.md

Add list of steering council and advisory board members to the website

---

.github/workflows/run-tests.yml
_includes/_head.html
index.md

Added `petsc.` to correct example.
Make tests run weekly to check that code is not outdated.

Update front page example

---

conference/2022.md

Links and deadline added with information from @david-kamensky

FEniCS 2022 abstract submission update

---

_test/test_code.py
assets/citations.bib
citing/index.md
download/archive.md
download/index.md
index.md

- Re-order citations (raise UFL)
- Expand Download (install) section

Citation and install updates

---

conference/2022.md

Add info regarding registration and payment link

2022 conference updates for registration

---

conference/2022.md

Add FEniCS 2022 schedule and program links

Add FEniCS 2022 schedule and program links

---

.github/workflows/run-tests.yml

Use stable image for testing

---

conference/index.md

Suggested by @meg-simula. Also stated in https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.466.2736&rep=rep1&type=pdf
Progress towards #4

FEniCS'10 was held at KTH

---

.github/workflows/run-tests.yml
_test/test_version_numbers.py
conference/2023.md

The deadline is somewhat arbitrary, please advise if another one is more suitable

Add abstract submission to FEniCS 2023 page

---

conference/2023.md

Add reminder that early registration is ending soon

---

conference/2023.md

Preparation for changes to be merged on April 1st. Do not merge before that date.

Update FEniCS 2023 registration after end of early registration

---

conference/2024.md

@finsberg please have a look as well:)

Add eventbrite registration

---

conference/2024.md

Add correct dates as pointed out by @francesco-ballarin in for https://github.com/FEniCS/web/pull/173#issuecomment-1959498856

Add correct dates to registration for fenics2024

---

index.md

Hi all, just found a broken link!

Fixed donation URL

---

_data/navbar.yml

Following #177 this fixes another link.
@francesco-ballarin I did a search and couldn't find anything else.

Fix donate link in navigation bar

---

conference/2024.md

Add grading system

---

_test/test_links.py
documentation/index.md
documentation/v0_9_0.md
index.md

Also removes the twitter/x logo

Add 0.9.0 release notes

---

conference/2025.md

Will wait till around June 5~6 to merge

Update FEniCS 2025 page: close registration, link to zenodo, prizes

---

conference/2025.md

@dajuno please help me check that I got the awardees right

Post conference FEniCS 2025 updates
